### ISSUE TITLE
Bug: Screenshot resolution

### ISSUE THREAD

**Issue by Arbarwings** [orangebeard-io/fitnesse-toolchain-listener#11]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| fitnesse-toolchain-listener | 1.0.4 |
| fitnesse | 20200501 |

### What is the expected behavior?
I would expect that the screenshots in the test result logs are in the original resolution, for example, 1920×1080.

### What is the actual behavior?
The screenshots in the log have a resolution of 200×132 pixels.

**Comment by tcnh** [comment]
The attachments also? 
Because the log-embedded base64 images are resized to 200 width on purpose to save space. Full res should be available in the image attachment

**Comment by Arbarwings** [comment]
There are no attachments available in the attachment tab of the log.

**Comment by tcnh** [comment]
Please test with 1.0.6 and confirm if this is resolved

**Comment by Arbarwings** [comment]
The screenshots look good with version 1.0.6!
