### ISSUE TITLE
Bug: Failed test aren't logged as an error type

### ISSUE THREAD

**Issue by Arbarwings** [orangebeard-io/fitnesse-toolchain-listener#12]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| fitnesse-toolchain-listener | 1.0.4 |
| fitnesse | 20200501 |

### What is the expected behavior?
I would expect that failed tests are reported as an error log type.

### What is the actual behavior?
Failed tests are reported as an info log type.

**Comment by tcnh** [comment]
Please test with 1.0.6 and confirm if this is resolved

**Comment by Arbarwings** [comment]
The failed tests are now logged as an error type in version 1.0.6.
